#!/usr/bin/env python3
"""Regenerate references/INDEX.md and references/_full.md from the reference files.

The reference files are the source of truth. This script derives two things from
them so neither can drift:

  INDEX.md   the routing table an agent reads first: one row per file, its
             purpose, its size, and the questions it answers. This is what makes
             the split navigable without loading everything.
  _full.md   the whole reference set concatenated, with a table of contents, for
             a person who wants to read it end to end. Generated, never edited.

Run it after adding, renaming or re-scoping any reference file:

    python3 scripts/build_index.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REFS = Path(__file__).resolve().parent.parent / "references"
GENERATED = {"INDEX.md", "_full.md"}

# One line per file, written by hand because "what question does this answer" is
# a judgment a script cannot make. A file present here but missing on disk, or
# on disk but missing here, is reported as an error rather than guessed at.
PURPOSE = {
    "00-house-style.md": "The defaults. Copy these if you want no decisions.",
    "01-narrative.md": "What the deck must argue, and in what order.",
    "02-artifact-and-length.md": "Which deck you are building, how many slides, how long.",
    "03-slide-by-slide.md": "What belongs on each individual slide.",
    "04-type-and-layout.md": "Text density, type scale, fonts, grid, alignment.",
    "05-color-and-access.md": "Palette architecture, contrast, dark mode, accessibility.",
    "06-charts-and-data.md": "Charts, tables, numbers, screenshots, sources, units.",
    "07-delivery.md": "Saying it out loud, and fielding interruptions.",
    "08-export-and-qa.md": "File formats, sending, and the pre-send checklist.",
    "09-failure-modes.md": "What goes wrong, and what to delete.",
    "10-sources.md": "Which rules are hard, which are soft, and where each came from.",
    "11-polarity-evidence.md": "Dark versus light: the actual evidence, the debunked claims, and a recommendation per scenario.",
}


def slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def headings(text: str) -> tuple[str, list[str]]:
    """The file's H1, and its H2s."""
    h1, h2s = "", []
    for line in text.split("\n"):
        if line.startswith("# ") and not h1:
            h1 = line[2:].strip()
        elif line.startswith("## "):
            h2s.append(line[3:].strip())
    return h1, h2s


def main() -> int:
    files = sorted(p for p in REFS.glob("*.md") if p.name not in GENERATED)
    if not files:
        print(f"no reference files in {REFS}", file=sys.stderr)
        return 1

    on_disk = {p.name for p in files}
    missing = set(PURPOSE) - on_disk
    unlisted = on_disk - set(PURPOSE)
    if missing or unlisted:
        for m in sorted(missing):
            print(f"  listed in PURPOSE but not on disk: {m}", file=sys.stderr)
        for u in sorted(unlisted):
            print(f"  on disk but not in PURPOSE: {u}", file=sys.stderr)
        print("fix PURPOSE in this script, then re-run", file=sys.stderr)
        return 1

    idx = [
        "# Reference index",
        "",
        "Read this file first, then read only the file you need. Nothing here is",
        "loaded automatically: the skill's own SKILL.md carries the enforced",
        "thresholds, and these files hold the reasoning and the citations.",
        "",
        "| File | Answers | Words |",
        "|---|---|---|",
    ]
    total = 0
    detail = []
    full = [
        "# Startup Pitch Deck and Presentation Best Practices",
        "",
        "Generated by `scripts/build_index.py`. Do not edit: edit the files in",
        "`references/` instead.",
        "",
        "## Contents",
        "",
    ]

    for p in files:
        text = p.read_text()
        h1, h2s = headings(text)
        words = len(text.split())
        total += words
        idx.append(f"| [`{p.name}`]({p.name}) | {PURPOSE[p.name]} | {words:,} |")
        detail.append((p.name, h1 or p.stem, h2s))
        full.append(f"- [{h1 or p.stem}](#{slug(h1 or p.stem)})")

    idx += ["", f"Total {total:,} words across {len(files)} files.", ""]
    idx += ["## What is in each file", ""]
    for name, h1, h2s in detail:
        idx.append(f"**[`{name}`]({name})** {h1}")
        idx.append("")
        for h in h2s:
            idx.append(f"- {h}")
        idx.append("")

    (REFS / "INDEX.md").write_text("\n".join(idx).rstrip() + "\n")

    full.append("")
    for p in files:
        full.append("---")
        full.append("")
        full.append(p.read_text().rstrip())
        full.append("")
    full_text = "\n".join(full).rstrip() + "\n"
    (REFS / "_full.md").write_text(full_text)

    print(f"INDEX.md   {len(files)} files, {total:,} words")
    print(f"_full.md   {len(full_text.split()):,} words")
    for name, h1, h2s in detail:
        print(f"  {name:26} {len(h2s):>2} sections  {h1[:44]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
