#!/usr/bin/env python3
"""Generate every per-assistant rule file from the one master, rules/core.md.

The master carries two placeholders: {{ASSISTANT}} for the assistant's name and
{{USER}} for the user's label. Each output fills them in for its own tool and
drops what that tool cannot use. Claude Code keeps the injection markers, because
its hook reads the block between them. ChatGPT and Cursor have no hooks, so their
copies lose the markers and the note about the hook.

Outputs, all relative to the kit root:

    claude/CLAUDE.md                 always-on file for Claude Code
    chatgpt/AGENTS.md                Codex AGENTS.md and a ChatGPT Project's instructions
    chatgpt/custom-instructions.txt  the Core as plain text; two labeled parts only if it outgrows 1500 characters
    chatgpt/writing-style.md         the writing-style skill as one upload
    chatgpt/pitch-deck.md            the pitch-deck skill as one upload
    cursor/user-rules.md             for Cursor's User Rules box

Standard library only. Paths resolve against this file, so it runs from any cwd:

    python3 scripts/build.py --user "Me"

Without --user the label comes from scripts/user.local when that file exists,
so check.sh can rebuild without resetting it.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

KIT = Path(__file__).resolve().parent.parent
CORE = KIT / "rules" / "core.md"
SKILLS = KIT / "claude" / "skills"
USER_FILE = KIT / "scripts" / "user.local"
START = "<!-- core:start -->"
END = "<!-- core:end -->"
BOX_LIMIT = 1500  # characters each ChatGPT custom-instructions box accepts
BOX_HEADERS = ("== Part 1: paste into the first custom-instructions box ==",
               "== Part 2: paste into the second custom-instructions box ==")
GENERATED_NOTE = "Generated by scripts/build.py from rules/core.md. Edit the master, then rebuild."


def fill(text: str, assistant: str, user: str) -> str:
    return text.replace("{{ASSISTANT}}", assistant).replace("{{USER}}", user)


def without_hook_note(text: str) -> str:
    """Drop the paragraph between the title and the start marker.

    That paragraph explains the hook. A tool without hooks has no use for it.
    """
    lines = text.split("\n")
    if START not in lines:
        sys.exit(f"{CORE} has no {START} marker")
    return "\n".join([lines[0], ""] + lines[lines.index(START):])


def without_markers(text: str) -> str:
    return "\n".join(line for line in text.split("\n")
                     if line.strip() not in (START, END))


def core_bullets(text: str) -> list[str]:
    body = text.partition(START)[2].partition(END)[0]
    bullets = [line[2:].strip() for line in body.split("\n") if line.startswith("- ")]
    if not bullets:
        sys.exit(f"{CORE} has no bullets between the markers")
    return bullets


def plain(line: str) -> str:
    """Markdown bullet to plain text: no bold, no code spans."""
    return re.sub(r"[*`]", "", line)


def split_front_matter(text: str) -> tuple[str, str]:
    """YAML front matter (with its fences) and the body, or empty and the text."""
    if not text.startswith("---\n"):
        return "", text
    close = text.find("\n---\n", 4)
    if close < 0:
        return "", text
    return text[:close + 5], text[close + 5:]


def read(path: Path) -> str:
    if not path.is_file():
        sys.exit(f"missing source file: {path}")
    return path.read_text(encoding="utf-8")


def bundle(skill: str, parts: list[Path], purpose: str) -> str:
    """One markdown file: SKILL.md, then each part under a '## File:' heading."""
    front, body = split_front_matter(read(SKILLS / skill / "SKILL.md"))
    note = (f"<!-- Generated by scripts/build.py from claude/skills/{skill}. "
            f"{purpose} Do not edit. -->")
    out = [front.rstrip("\n"), "", note, "", "## File: SKILL.md", "", body.strip("\n")]
    for part in parts:
        name = part.relative_to(SKILLS / skill).as_posix()
        out += ["", f"## File: {name}", "", read(part).strip("\n")]
    return "\n".join(out).lstrip("\n") + "\n"


def write(path: Path, text: str, extra: str = "") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"{path.relative_to(KIT).as_posix()}{extra}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    default_user = USER_FILE.read_text(encoding="utf-8").strip() if USER_FILE.is_file() else "Me"
    ap.add_argument("--user", default=default_user or "Me",
                    help="label for the user in the next-step line (default: scripts/user.local, else Me)")
    ap.add_argument("--assistant-claude", default="Claude")
    ap.add_argument("--assistant-chatgpt", default="ChatGPT")
    ap.add_argument("--assistant-cursor", default="Cursor")
    args = ap.parse_args()

    master = read(CORE)
    if START not in master or END not in master:
        sys.exit(f"{CORE} must contain both {START} and {END}")

    # Claude Code: the whole master, markers kept for the hook.
    claude = fill(master, args.assistant_claude, args.user)
    write(KIT / "claude" / "CLAUDE.md", f"<!-- {GENERATED_NOTE} -->\n{claude}")

    # ChatGPT and Codex: no hooks, so no markers and no hook note.
    agents = without_markers(without_hook_note(fill(master, args.assistant_chatgpt, args.user)))
    agents_note = ("<!-- Serves both ~/.codex/AGENTS.md and the instructions box of a "
                   f"ChatGPT Project. {GENERATED_NOTE} -->")
    write(KIT / "chatgpt" / "AGENTS.md", f"{agents_note}\n{agents}")

    # Cursor: same shape, for the User Rules box.
    cursor = without_markers(without_hook_note(fill(master, args.assistant_cursor, args.user)))
    cursor_note = f"<!-- Paste into Cursor under Settings, Rules, User Rules. {GENERATED_NOTE} -->"
    write(KIT / "cursor" / "user-rules.md", f"{cursor_note}\n{cursor}")

    # ChatGPT custom instructions: the Core bullets as plain text, one per line.
    # A box takes 1500 characters; if the Core outgrows one, split into two
    # labeled parts for the two boxes on the settings page.
    lines = [plain(fill(b, args.assistant_chatgpt, args.user)) for b in core_bullets(master)]
    parts: list[list[str]] = [[]]
    for line in lines:
        if len(line) > BOX_LIMIT:
            sys.exit(f"a Core bullet is {len(line)} characters, over the {BOX_LIMIT} a box accepts: {line[:60]}")
        if parts[-1] and len("\n".join(parts[-1] + [line])) > BOX_LIMIT:
            parts.append([])
        parts[-1].append(line)
    if len(parts) > 2:
        sys.exit("the Core no longer fits two custom-instructions boxes; tighten rules/core.md")
    sizes = [len("\n".join(p)) for p in parts]
    if len(parts) == 1:
        box = "\n".join(parts[0])
    else:
        box = "\n\n".join(f"{BOX_HEADERS[i]}\n" + "\n".join(p) for i, p in enumerate(parts))
    write(KIT / "chatgpt" / "custom-instructions.txt", box + "\n",
          "  (" + " and ".join(f"{s} of {BOX_LIMIT}" for s in sizes) + " characters)")

    # The two skills, each as one upload for a ChatGPT Project.
    refs = SKILLS / "writing-style" / "references"
    parts = sorted(p for p in refs.glob("*.md") if p.name != "INDEX.md")
    write(KIT / "chatgpt" / "writing-style.md",
          bundle("writing-style", parts, "Upload it to a ChatGPT Project as one file."))
    write(KIT / "chatgpt" / "pitch-deck.md",
          bundle("pitch-deck", [SKILLS / "pitch-deck" / "references" / "_full.md"],
                 "Upload it to a ChatGPT Project as one file."))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
